blank_issues_enabled: true
contact_links:
  - name: Transaction Form 1
    url: https://treasuryguild.github.io/treasury-v3/
    about: Fill in this form when you make a transaction (Complete form 1 and 2)
  - name: Transaction Form 2
    url: https://github.com/treasuryguild/Training-and-Automation/issues/new
    about: Fill in this form after you made a transaction (Complete form 1 and 2)
  - name: Tasks/Misc/Expenses
    url: https://docs.google.com/forms/d/e/1FAIpQLSdB1NDk_7eWQ7NBbFGcvGadqFGMD3QEv12o8Tnp4S-pYY_tVg/viewform?usp=sf_link
    about: Google form for tasks/misc/expense ADA requests to be completed by Co-/Proposer
