blank_issues_enabled: false
contact_links:
  - name: Transaction Form 2
    url: https://treasuryguild.github.io/Training-and-Automation/
    about: Fill in this form when you make a transaction (Complete form 1 and 2)
  - name: Tasks/Misc/Expenses
    url: https://docs.google.com/forms/d/e/1FAIpQLSfRqm6wvX4gBN-V3bQIbFO4UnO8FofR4px8tsFcfL04sb-l9A/viewform?usp=sf_link
    about: Google form for tasks/misc/expense ADA requests to be completed by Co-/Proposer
